main:
  - name: About
    url: '#about'
    weight: 1
  - name: Research
    url: /research/
    weight: 2
  - name: Teaching
    url: /teaching/
    weight: 3
  - name: CV
    url: /pdf/Ke_Lyu_CV.pdf
    weight: 4